(() => {
  const $ = (sel) => document.querySelector(sel);
  const esc = (v = "") => String(v).replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const order = ["taiex", "otc", "tx", "turnover", "breadth", "usdTwd", "foreignSpot", "foreignTx", "putCall", "margin"];
  const labels = {
    taiex: "TAIEX", otc: "櫃買指數", tx: "臺指期 TX", turnover: "上市成交金額", breadth: "市場廣度",
    usdTwd: "USD/TWD", foreignSpot: "外資現貨", foreignTx: "外資 TX 淨部位", putCall: "Put/Call", margin: "融資餘額"
  };

  function stateLabel(state) {
    return ({licensed_intraday:"盤中", official_close:"官方收盤", official_daily:"官方日資料", official_afterhours:"官方盤後", stale:"沿用上一筆", waiting:"等待", missing:"N/A"})[state] || state || "—";
  }


  function riskClass(score) {
    if (score == null || Number.isNaN(score)) return "na";
    if (score >= 70) return "strong-on";
    if (score >= 55) return "on";
    if (score >= 45) return "neutral";
    if (score >= 30) return "off";
    return "strong-off";
  }

  function renderRisk(data) {
    const grid = $("#autoMetricGrid");
    if (!grid) return;
    let panel = $("#autoRiskPanel");
    if (!panel) {
      panel = document.createElement("section");
      panel.id = "autoRiskPanel";
      panel.className = "auto-risk-panel";
      grid.parentNode.insertBefore(panel, grid);
    }

    const risk = data.risk || {};
    const score = typeof risk.score === "number" ? risk.score : null;
    const cls = riskClass(score);
    const drivers = Array.isArray(risk.drivers) ? risk.drivers : [];
    const confidence = Number.isFinite(Number(risk.confidence)) ? Number(risk.confidence) : 0;

    panel.dataset.risk = cls;
    panel.innerHTML = `
      <div class="auto-risk-score">
        <div class="auto-risk-kicker">MARKET RISK SCORE</div>
        <div class="auto-risk-number">${score == null ? "N/A" : esc(score.toFixed(0))}</div>
        <div class="auto-risk-label">${esc(risk.label || "資料不足")}</div>
        <div class="auto-risk-confidence">模型完整度 ${esc(confidence)}%</div>
      </div>
      <div class="auto-risk-body">
        <div class="auto-risk-title">目前市場主導力量</div>
        <div class="auto-risk-drivers">
          ${drivers.length ? drivers.map(d => `
            <div class="auto-risk-driver" data-direction="${esc(d.direction || "neutral")}">
              <span>${esc(d.name || "")}</span>
              <strong>${esc(d.reason || "")}</strong>
            </div>
          `).join("") : `<div class="auto-risk-empty">等待足夠資料建立風險判讀。</div>`}
        </div>
        <div class="auto-risk-note">${esc(risk.note || "")}</div>
      </div>
    `;
  }

  function render(data) {
    const badge = $("#autoUpdateBadge");
    const generated = $("#autoGeneratedAt");
    const phase = $("#autoMarketPhase");
    const next = $("#autoNextExpected");
    const grid = $("#autoMetricGrid");
    const feed = $("#autoFeedNotice");
    const errors = $("#autoErrors");
    if (!grid) return;

    const ok = !data.errors || data.errors.length === 0;
    badge.textContent = ok ? "AUTO · OK" : `AUTO · ${data.errors.length} SOURCE WARNING`;
    badge.dataset.state = ok ? "ok" : "warn";
    generated.textContent = data.generatedAt || "N/A";
    phase.textContent = data.marketPhase || "N/A";
    next.textContent = data.nextExpected || "N/A";

    renderRisk(data);

    grid.innerHTML = order.map(key => {
      const m = (data.metrics || {})[key] || {};
      return `<article class="auto-metric" data-state="${esc(m.state || "missing")}">
        <div class="auto-metric-top"><span>${esc(labels[key])}</span><span class="auto-state">${esc(stateLabel(m.state))}</span></div>
        <strong>${esc(m.value || "N/A")}</strong>
        <div class="auto-change">${esc(m.change || "")}</div>
        <div class="auto-asof">資料時間 ${esc(m.asOf || "N/A")} · ${esc(m.source || "")}</div>
      </article>`;
    }).join("");

    const f = data.intradayFeed || {};
    feed.dataset.state = f.state || "not_configured";
    feed.innerHTML = `<strong>${esc(f.label || "盤中資料源狀態")}</strong><span>${esc(f.note || "")}</span>`;

    if (data.errors && data.errors.length) {
      errors.hidden = false;
      errors.innerHTML = `<strong>本次更新有部分來源失敗：</strong>${data.errors.slice(0, 4).map(e => `<span>${esc(e.source)}：${esc(e.message)}</span>`).join("")}`;
    } else {
      errors.hidden = true;
      errors.innerHTML = "";
    }
  }

  async function renderTrend() {
    const panel = $("#autoRiskPanel");
    if (!panel) return;
    try {
      const r = await fetch(`data/live-history.json?t=${Date.now()}`, { cache: "no-store" });
      if (!r.ok) return;
      const rows = await r.json();
      const points = (Array.isArray(rows) ? rows : [])
        .filter(x => x && x.risk && typeof x.risk.score === "number")
        .slice(-8);
      if (!points.length) return;

      let trend = panel.querySelector(".auto-risk-trend");
      if (!trend) {
        trend = document.createElement("div");
        trend.className = "auto-risk-trend";
        panel.querySelector(".auto-risk-body")?.appendChild(trend);
      }

      trend.innerHTML = `
        <span class="auto-risk-trend-label">近期風險分數</span>
        <div class="auto-risk-spark">
          ${points.map(p => {
            const s = Math.max(0, Math.min(100, Number(p.risk.score)));
            const dt = String(p.generatedAt || "").slice(11,16);
            return `<div class="auto-risk-bar-wrap" title="${esc(dt)} · ${esc(s.toFixed(0))}">
              <div class="auto-risk-bar" style="height:${Math.max(8, s)}%"></div>
              <span>${esc(s.toFixed(0))}</span>
            </div>`;
          }).join("")}
        </div>
      `;
    } catch (_) {}
  }

  async function load() {
    try {
      const response = await fetch(`data/live.json?t=${Date.now()}`, { cache: "no-store" });
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      render(await response.json());
      renderTrend();
    } catch (error) {
      const badge = $("#autoUpdateBadge");
      if (badge) { badge.textContent = "AUTO · LOAD ERROR"; badge.dataset.state = "warn"; }
      const errors = $("#autoErrors");
      if (errors) { errors.hidden = false; errors.textContent = `自動資料讀取失敗：${error.message}`; }
    }
  }

  load();
  setInterval(load, 5 * 60 * 1000);
})();
