(() => {
  const $ = (sel) => document.querySelector(sel);
  const esc = (v = "") => String(v).replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const order = ["taiex", "otc", "tx", "turnover", "breadth", "usdTwd", "foreignSpot", "foreignTx", "putCall", "margin"];
  const labels = {
    taiex: "TAIEX", otc: "櫃買指數", tx: "臺指期 TX", turnover: "上市成交金額", breadth: "市場廣度",
    usdTwd: "USD/TWD", foreignSpot: "外資現貨", foreignTx: "外資 TX 淨部位", putCall: "Put/Call", margin: "融資餘額"
  };

  function stateLabel(state) {
    return ({licensed_intraday:"授權盤中", official_close:"官方收盤", official_daily:"官方日資料", official_afterhours:"官方盤後", stale:"沿用上一筆", waiting:"等待", missing:"N/A"})[state] || state || "—";
  }


  function riskClass(score) {
    if (score == null || Number.isNaN(score)) return "na";
    if (score >= 70) return "strong-on";
    if (score >= 55) return "on";
    if (score >= 45) return "neutral";
    if (score >= 30) return "off";
    return "strong-off";
  }

  function renderRisk(data) {
    const grid = $("#autoMetricGrid");
    if (!grid) return;
    let panel = $("#autoRiskPanel");
    if (!panel) {
      panel = document.createElement("section");
      panel.id = "autoRiskPanel";
      panel.className = "auto-risk-panel";
      grid.parentNode.insertBefore(panel, grid);
    }

    const risk = data.risk || {};
    const score = typeof risk.score === "number" ? risk.score : null;
    const cls = riskClass(score);
    const drivers = Array.isArray(risk.drivers) ? risk.drivers : [];
    const confidence = Number.isFinite(Number(risk.confidence)) ? Number(risk.confidence) : 0;

    panel.dataset.risk = cls;
    panel.innerHTML = `
      <div class="auto-risk-score">
        <div class="auto-risk-kicker">MARKET RISK SCORE</div>
        <div class="auto-risk-number">${score == null ? "N/A" : esc(score.toFixed(0))}</div>
        <div class="auto-risk-label">${esc(risk.label || "資料不足")}</div>
        <div class="auto-risk-confidence">模型完整度 ${esc(confidence)}%</div>
      </div>
      <div class="auto-risk-body">
        <div class="auto-risk-title">目前市場主導力量</div>
        <div class="auto-risk-drivers">
          ${drivers.length ? drivers.map(d => `
            <div class="auto-risk-driver" data-direction="${esc(d.direction || "neutral")}">
              <span>${esc(d.name || "")}</span>
              <strong>${esc(d.reason || "")}</strong>
            </div>
          `).join("") : `<div class="auto-risk-empty">等待足夠資料建立風險判讀。</div>`}
        </div>
        <div class="auto-risk-note">${esc(risk.note || "")}</div>
      </div>
    `;
  }

  function render(data) {
    const badge = $("#autoUpdateBadge");
    const generated = $("#autoGeneratedAt");
    const phase = $("#autoMarketPhase");
    const next = $("#autoNextExpected");
    const grid = $("#autoMetricGrid");
    const feed = $("#autoFeedNotice");
    const errors = $("#autoErrors");
    if (!grid) return;

    const ok = !data.errors || data.errors.length === 0;
    badge.textContent = ok ? "AUTO · OK" : `AUTO · ${data.errors.length} SOURCE WARNING`;
    badge.dataset.state = ok ? "ok" : "warn";
    generated.textContent = data.generatedAt || "N/A";
    phase.textContent = data.marketPhase || "N/A";
    next.textContent = data.nextExpected || "N/A";

    renderRisk(data);

    grid.innerHTML = order.map(key => {
      const m = (data.metrics || {})[key] || {};
      return `<article class="auto-metric" data-state="${esc(m.state || "missing")}">
        <div class="auto-metric-top"><span>${esc(labels[key])}</span><span class="auto-state">${esc(stateLabel(m.state))}</span></div>
        <strong>${esc(m.value || "N/A")}</strong>
        <div class="auto-change">${esc(m.change || "")}</div>
        <div class="auto-asof">資料時間 ${esc(m.asOf || "N/A")} · ${esc(m.source || "")}</div>
      </article>`;
    }).join("");

    const f = data.intradayFeed || {};
    feed.dataset.state = f.state || "not_configured";
    feed.innerHTML = `<strong>${esc(f.label || "盤中資料源狀態")}</strong><span>${esc(f.note || "")}</span>${f.vendor ? `<em>${esc(f.vendor)}</em>` : ""}`;

    if (data.errors && data.errors.length) {
      errors.hidden = false;
      errors.innerHTML = `<strong>本次更新有部分來源失敗：</strong>${data.errors.slice(0, 4).map(e => `<span>${esc(e.source)}：${esc(e.message)}</span>`).join("")}`;
    } else {
      errors.hidden = true;
      errors.innerHTML = "";
    }
  }

  async function renderTrend() {
    const panel = $("#autoRiskPanel");
    if (!panel) return;
    try {
      const r = await fetch(`data/live-history.json?t=${Date.now()}`, { cache: "no-store" });
      if (!r.ok) return;
      const rows = await r.json();
      const points = (Array.isArray(rows) ? rows : [])
        .filter(x => x && x.risk && typeof x.risk.score === "number")
        .slice(-8);
      if (!points.length) return;

      let trend = panel.querySelector(".auto-risk-trend");
      if (!trend) {
        trend = document.createElement("div");
        trend.className = "auto-risk-trend";
        panel.querySelector(".auto-risk-body")?.appendChild(trend);
      }

      trend.innerHTML = `
        <span class="auto-risk-trend-label">近期風險分數</span>
        <div class="auto-risk-spark">
          ${points.map(p => {
            const s = Math.max(0, Math.min(100, Number(p.risk.score)));
            const dt = String(p.generatedAt || "").slice(11,16);
            return `<div class="auto-risk-bar-wrap" title="${esc(dt)} · ${esc(s.toFixed(0))}">
              <div class="auto-risk-bar" style="height:${Math.max(8, s)}%"></div>
              <span>${esc(s.toFixed(0))}</span>
            </div>`;
          }).join("")}
        </div>
      `;
    } catch (_) {}
  }


  function renderAutoBrief(brief) {
    const grid = $("#autoMetricGrid");
    if (!grid) return;
    let panel = $("#autoBriefPanel");
    if (!panel) {
      panel = document.createElement("section");
      panel.id = "autoBriefPanel";
      panel.className = "auto-brief-panel";
      grid.parentNode.insertBefore(panel, grid);
    }

    const daily = brief?.daily || {};
    const weekly = brief?.weekly || {};
    panel.innerHTML = `
      <div class="auto-brief-head">
        <div>
          <span class="auto-brief-kicker">AUTO RESEARCH BRIEF</span>
          <h3>自動市場判讀</h3>
        </div>
        <div class="auto-brief-tabs" role="group" aria-label="自動報告模式">
          <button class="auto-brief-tab active" data-brief-mode="daily">日報</button>
          <button class="auto-brief-tab" data-brief-mode="weekly">週報</button>
        </div>
      </div>
      <div class="auto-brief-content" data-brief-view="daily"></div>
      <div class="auto-brief-content" data-brief-view="weekly" hidden></div>
    `;

    const renderDaily = () => {
      const target = panel.querySelector('[data-brief-view="daily"]');
      const bullets = Array.isArray(daily.quickTake) ? daily.quickTake : [];
      const invalidation = Array.isArray(daily.invalidation) ? daily.invalidation : [];
      target.innerHTML = `
        <div class="auto-brief-hero" data-tone="${esc(daily.tone || 'neutral')}">
          <div><span>即時判讀</span><strong>${esc(daily.label || '資料不足')}</strong></div>
          <div class="auto-brief-score">${daily.score == null ? 'N/A' : esc(Number(daily.score).toFixed(0))}</div>
        </div>
        ${daily.resonance ? `<div class="auto-resonance" data-tone="${esc(daily.resonance.tone || 'neutral')}">
          <div><span>CROSS-MARKET RESONANCE</span><strong>${esc(daily.resonance.label || '')}</strong></div>
          <div class="auto-resonance-score">${daily.resonance.score == null ? 'N/A' : esc(Number(daily.resonance.score).toFixed(0))}</div>
          <p>${esc(daily.resonance.note || '')}</p>
        </div>` : ''}
        <p class="auto-brief-headline">${esc(daily.headline || '')}</p>
        <div class="auto-brief-bullets">${bullets.map(x => `<div><span>•</span><p>${esc(x)}</p></div>`).join('')}</div>
        <div class="auto-brief-outlook">
          <div><span>短線 1–5 日</span><p>${esc(daily.shortView || '')}</p></div>
          <div><span>波段 2–8 週</span><p>${esc(daily.swingView || '')}</p></div>
        </div>
        <div class="auto-brief-invalidation">
          <span>改判條件</span>
          <ol>${invalidation.map(x => `<li>${esc(x)}</li>`).join('')}</ol>
        </div>
        <div class="auto-brief-note">${esc(daily.dataNote || '')}</div>
      `;
    };

    const renderWeekly = () => {
      const target = panel.querySelector('[data-brief-view="weekly"]');
      const bullets = Array.isArray(weekly.quickTake) ? weekly.quickTake : [];
      const stats = Array.isArray(weekly.stats) ? weekly.stats : [];
      target.innerHTML = `
        <div class="auto-brief-weekly-status" data-state="${esc(weekly.status || 'collecting')}">
          <strong>${esc(weekly.status === 'ready' ? '自動週報' : '週報資料累積中')}</strong>
          <span>${esc(weekly.headline || '')}</span>
        </div>
        ${stats.length ? `<div class="auto-brief-stats">${stats.map(s => `<div><span>${esc(s.label)}</span><strong>${s.value == null ? 'N/A' : esc(s.value)}</strong></div>`).join('')}</div>` : ''}
        <div class="auto-brief-bullets">${bullets.map(x => `<div><span>•</span><p>${esc(x)}</p></div>`).join('')}</div>
        <div class="auto-brief-note">${esc(weekly.dataNote || '')}</div>
      `;
    };

    renderDaily();
    renderWeekly();

    panel.querySelectorAll('.auto-brief-tab').forEach(btn => {
      btn.addEventListener('click', () => {
        const mode = btn.dataset.briefMode;
        panel.querySelectorAll('.auto-brief-tab').forEach(x => x.classList.toggle('active', x === btn));
        panel.querySelectorAll('[data-brief-view]').forEach(view => { view.hidden = view.dataset.briefView !== mode; });
      });
    });
  }


  function globalMetricCard(label, row = {}) {
    return `<article class="auto-global-metric" data-state="${esc(row.state || 'missing')}">
      <div><span>${esc(label)}</span><small>${esc(row.source || '')}</small></div>
      <strong>${esc(row.display || 'N/A')}</strong>
      <p>${esc(row.change || '')}</p>
      <em>${esc(row.asOf || 'N/A')}</em>
    </article>`;
  }

  function renderGlobal(globalData) {
    const grid = $("#autoMetricGrid");
    if (!grid) return;
    let panel = $("#autoGlobalPanel");
    if (!panel) {
      panel = document.createElement("section");
      panel.id = "autoGlobalPanel";
      panel.className = "auto-global-panel";
      grid.parentNode.insertBefore(panel, grid);
    }

    const macro = globalData?.macro || {};
    const equity = globalData?.equity || {};
    const risk = globalData?.risk || {};
    const news = Array.isArray(globalData?.news) ? globalData.news : [];
    const events = Array.isArray(globalData?.events) ? globalData.events : [];
    const reaction = globalData?.reaction || {};
    const errors = Array.isArray(globalData?.errors) ? globalData.errors : [];
    const equityFeed = globalData?.equityFeed || {};
    const riskScore = typeof risk.score === 'number' ? risk.score : null;

    panel.innerHTML = `
      <div class="auto-global-head">
        <div>
          <span class="auto-global-kicker">GLOBAL MACRO & OFFICIAL NEWS</span>
          <h3>全球宏觀與官方消息</h3>
        </div>
        <div class="auto-global-risk" data-risk="${esc(riskClass(riskScore))}">
          <span>GLOBAL MACRO</span>
          <strong>${riskScore == null ? 'N/A' : esc(riskScore.toFixed(0))}</strong>
          <em>${esc(risk.label || '資料不足')}</em>
        </div>
      </div>

      <div class="auto-global-drivers">
        ${(Array.isArray(risk.drivers) && risk.drivers.length) ? risk.drivers.map(d => `
          <div data-direction="${esc(d.direction || 'neutral')}"><span>${esc(d.name || '')}</span><strong>${esc(d.reason || '')}</strong></div>
        `).join('') : '<span>全球宏觀資料累積中。</span>'}
      </div>

      <div class="auto-global-section-title"><span>官方宏觀資料</span><em>${esc(globalData?.generatedAt || '')}</em></div>
      <div class="auto-global-grid">
        ${globalMetricCard('美國10Y', macro.us10y)}
        ${globalMetricCard('10Y實質利率', macro.real10y)}
        ${globalMetricCard('2Y–10Y利差', macro.spread2s10s)}
        ${globalMetricCard('Brent', macro.brent)}
        ${globalMetricCard('美國CPI', macro.cpi)}
        ${globalMetricCard('失業率', macro.unemployment)}
      </div>

      <div class="auto-global-section-title"><span>官方跨資產反應</span><em>不使用未授權股價指數</em></div>
      <div class="auto-global-reaction" data-tone="${esc(reaction.tone || 'neutral')}">
        <strong>${esc(reaction.label || '資料累積中')}</strong>
        <p>${esc(reaction.note || '')}</p>
        <div>${(Array.isArray(reaction.bullets) ? reaction.bullets : []).map(x => `<span>${esc(x)}</span>`).join('')}</div>
      </div>

      <div class="auto-global-section-title"><span>未來 1–2 週官方事件</span><em>台北時間</em></div>
      <div class="auto-event-calendar">
        ${events.length ? events.slice(0, 8).map(e => `
          <article>
            <time>${esc(e.scheduledAt || '')}</time>
            <div>
              <div><span>${esc(e.source || '')}</span><em>${'★'.repeat(Math.max(1, Math.min(5, Number(e.impact) || 1)))}</em></div>
              <a href="${esc(e.link || '#')}" target="_blank" rel="noopener noreferrer">${esc(e.title || '')}</a>
              <p>${esc(e.watch || '')}</p>
            </div>
          </article>
        `).join('') : '<div class="auto-news-empty">未來 14 天沒有符合目前篩選條件的高影響官方事件。</div>'}
      </div>

      <div class="auto-global-equity-notice" data-state="${esc(equityFeed.state || 'not_configured')}">
        <strong>${esc(equityFeed.label || '全球股票指數授權源尚未設定')}</strong>
        <span>${esc(equityFeed.note || '')}</span>
      </div>
      <div class="auto-global-equity-grid">
        ${globalMetricCard('S&P 500', equity.sp500)}
        ${globalMetricCard('Nasdaq', equity.nasdaq)}
        ${globalMetricCard('SOX', equity.sox)}
        ${globalMetricCard('VIX', equity.vix)}
      </div>

      <div class="auto-global-section-title"><span>官方消息</span><em>只收 Fed / BLS 原始來源</em></div>
      <div class="auto-official-news">
        ${news.length ? news.slice(0, 6).map(n => `
          <article>
            <div class="auto-news-meta">
              <span>${esc(n.source || '')}</span>
              <span>${'★'.repeat(Math.max(1, Math.min(5, Number(n.impact) || 1)))}</span>
              <em>${esc(n.category || '')}</em>
            </div>
            <a href="${esc(n.link || '#')}" target="_blank" rel="noopener noreferrer">${esc(n.title || '')}</a>
            <p>${esc(n.transmission || '')}</p>
            <small>${esc(n.publishedAt || '')}</small>
          </article>
        `).join('') : '<div class="auto-news-empty">目前沒有新的高相關官方事件。</div>'}
      </div>

      ${errors.length ? `<details class="auto-global-errors"><summary>全球資料 ${errors.length} 個 warning</summary>${errors.slice(0, 6).map(e => `<span>${esc(e.source)}：${esc(e.message)}</span>`).join('')}</details>` : ''}
    `;
  }

  async function loadGlobal() {
    try {
      const r = await fetch(`data/global.json?t=${Date.now()}`, { cache: "no-store" });
      if (!r.ok) return;
      renderGlobal(await r.json());
    } catch (_) {}
  }

  async function loadBrief() {
    try {
      const r = await fetch(`data/auto-brief.json?t=${Date.now()}`, { cache: "no-store" });
      if (!r.ok) return;
      renderAutoBrief(await r.json());
    } catch (_) {}
  }

  async function load() {
    try {
      const response = await fetch(`data/live.json?t=${Date.now()}`, { cache: "no-store" });
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      render(await response.json());
      renderTrend();
      loadBrief();
      loadGlobal();
    } catch (error) {
      const badge = $("#autoUpdateBadge");
      if (badge) { badge.textContent = "AUTO · LOAD ERROR"; badge.dataset.state = "warn"; }
      const errors = $("#autoErrors");
      if (errors) { errors.hidden = false; errors.textContent = `自動資料讀取失敗：${error.message}`; }
    }
  }

  load();
  setInterval(load, 5 * 60 * 1000);
})();
