(() => {
  const $ = (sel) => document.querySelector(sel);
  const esc = (v = "") => String(v).replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const order = ["taiex", "otc", "tx", "turnover", "breadth", "usdTwd", "foreignSpot", "foreignTx", "putCall", "margin"];
  const labels = {
    taiex: "TAIEX", otc: "櫃買指數", tx: "臺指期 TX", turnover: "上市成交金額", breadth: "市場廣度",
    usdTwd: "USD/TWD", foreignSpot: "外資現貨", foreignTx: "外資 TX 淨部位", putCall: "Put/Call", margin: "融資餘額"
  };

  function stateLabel(state) {
    return ({licensed_intraday:"盤中", official_close:"官方收盤", official_daily:"官方日資料", official_afterhours:"官方盤後", stale:"沿用上一筆", waiting:"等待", missing:"N/A"})[state] || state || "—";
  }

  function render(data) {
    const badge = $("#autoUpdateBadge");
    const generated = $("#autoGeneratedAt");
    const phase = $("#autoMarketPhase");
    const next = $("#autoNextExpected");
    const grid = $("#autoMetricGrid");
    const feed = $("#autoFeedNotice");
    const errors = $("#autoErrors");
    if (!grid) return;

    const ok = !data.errors || data.errors.length === 0;
    badge.textContent = ok ? "AUTO · OK" : `AUTO · ${data.errors.length} SOURCE WARNING`;
    badge.dataset.state = ok ? "ok" : "warn";
    generated.textContent = data.generatedAt || "N/A";
    phase.textContent = data.marketPhase || "N/A";
    next.textContent = data.nextExpected || "N/A";

    grid.innerHTML = order.map(key => {
      const m = (data.metrics || {})[key] || {};
      return `<article class="auto-metric" data-state="${esc(m.state || "missing")}">
        <div class="auto-metric-top"><span>${esc(labels[key])}</span><span class="auto-state">${esc(stateLabel(m.state))}</span></div>
        <strong>${esc(m.value || "N/A")}</strong>
        <div class="auto-change">${esc(m.change || "")}</div>
        <div class="auto-asof">資料時間 ${esc(m.asOf || "N/A")} · ${esc(m.source || "")}</div>
      </article>`;
    }).join("");

    const f = data.intradayFeed || {};
    feed.dataset.state = f.state || "not_configured";
    feed.innerHTML = `<strong>${esc(f.label || "盤中資料源狀態")}</strong><span>${esc(f.note || "")}</span>`;

    if (data.errors && data.errors.length) {
      errors.hidden = false;
      errors.innerHTML = `<strong>本次更新有部分來源失敗：</strong>${data.errors.slice(0, 4).map(e => `<span>${esc(e.source)}：${esc(e.message)}</span>`).join("")}`;
    } else {
      errors.hidden = true;
      errors.innerHTML = "";
    }
  }

  async function load() {
    try {
      const response = await fetch(`data/live.json?t=${Date.now()}`, { cache: "no-store" });
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      render(await response.json());
    } catch (error) {
      const badge = $("#autoUpdateBadge");
      if (badge) { badge.textContent = "AUTO · LOAD ERROR"; badge.dataset.state = "warn"; }
      const errors = $("#autoErrors");
      if (errors) { errors.hidden = false; errors.textContent = `自動資料讀取失敗：${error.message}`; }
    }
  }

  load();
  setInterval(load, 5 * 60 * 1000);
})();
